version: '3'

networks:
  backend:
    driver: bridge

services:

### Phoenix ###########################################
    app:
      build: ./phoenix1.4
      volumes:
        - ${APP_CODE_PATH_HOST}:/app
      ports:
        - "${PHOENIX_PORT}:4000"
        - "${WEBPACK_DEVSERVER_PORT}:8080"
      networks:
        - backend

### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/${COMPOSE_PROJECT_NAME}/postgres:/var/lib/postgresql/data
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      networks:
        - backend